services:
  moodle:
    build: .
    container_name: moodle-app
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - moodledata:/var/www/moodledata
    restart: always

  db:
    image: postgres:14
    container_name: moodle-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  moodledata:
  postgres_data:
