services:
  db:
    image: postgres:14
    container_name: moodle-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  moodle:
    image: moodlehq/moodle-php-apache:8.3
    container_name: moodle-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ../../:/var/www/html
      - ../../moodledata:/var/moodledata
    restart: always

volumes:
  postgres_data:
