name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for DB
        run: |
          until docker compose exec -T db pg_isready -U moodle_user; do 
            sleep 2
          done

      - name: Install Moodle
        run: |
          docker compose exec -T moodle bash -c "\
            php admin/cli/install.php \
              --non-interactive \
              --agree-license \
              --fullname='Test Site' \
              --shortname='Test' \
              --adminuser=admin \
              --adminpass=Admin123! \
              --adminemail=admin@example.com \
              --dbtype=pgsql \
              --dbhost=db \
              --dbname=${{ vars.POSTGRES_DB }} \
              --dbuser=${{ vars.POSTGRES_USER }} \
              --dbpass=${{ vars.POSTGRES_PASSWORD }} \
              --wwwroot=http://localhost:8080 \
              --dataroot=/var/www/moodledata && \
            chown www-data:www-data /var/www/html/config.php"

      - name: Run PHPUnit tests
        run: docker compose exec -T moodle phpunit --testsuite local_todolist_testsuite

      - name: Shut down
        if: always()
        run: docker compose down -v
