name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for DB to be ready
        run: |
          until docker compose exec -T db pg_isready -U moodle_user; do 
            sleep 2
          done

      - name: Clone Moodle in container
        run: |
          docker compose exec -T moodle bash -c "
            git clone --depth=1 -b MOODLE_401_STABLE https://github.com/moodle/moodle.git /var/www/html && \
            cd /var/www/html && \
            composer install"

      - name: Install Moodle & init PHPUnit
        run: |
          docker compose exec -T moodle php admin/cli/install.php \
            --non-interactive \
            --agree-license \
            --fullname="Test Site" \
            --shortname="Test" \
            --adminuser=admin \
            --adminpass=Admin123! \
            --adminemail=admin@example.com \
            --dbtype=pgsql \
            --dbhost=db \
            --dbname=${POSTGRES_DB} \
            --dbuser=${POSTGRES_USER} \
            --dbpass=${POSTGRES_PASSWORD} \
            --wwwroot=http://localhost:8080 \
            --dataroot=/var/moodledata

          docker compose exec -T moodle php admin/tool/phpunit/cli/init.php

      - name: Run PHPUnit tests
        run: docker compose exec -T moodle vendor/bin/phpunit local_local_todolist

      - name: Shut down
        if: always()
        run: docker compose down -v
